const Main = () => {
    return (
        <>
            <div id="about">About Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div id="skills">Skills Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div>MAIN Component</div>
            <div id="contacts">CONTACTS Component</div>
            <div>MAIN Component</div>
        </>
    )
}

export default Main;